import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const defaultTemplates = [
  {
    name: 'Brainstorming',
    description: 'A simple template for brainstorming ideas around a central topic',
    category: 'General',
    thumbnail: null,
    isPublic: true,
    data: {
      nodes: [
        {
          id: 'root',
          text: 'Main Topic',
          type: 'ROOT',
          parentId: null,
          positionX: 400,
          positionY: 300,
          width: 150,
          height: 50,
          style: { backgroundColor: '#3b82f6', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'idea1',
          text: 'Idea 1',
          type: 'CHILD',
          parentId: 'root',
          positionX: 200,
          positionY: 150,
          width: 120,
          height: 40,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'idea2',
          text: 'Idea 2',
          type: 'CHILD',
          parentId: 'root',
          positionX: 600,
          positionY: 150,
          width: 120,
          height: 40,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'idea3',
          text: 'Idea 3',
          type: 'CHILD',
          parentId: 'root',
          positionX: 200,
          positionY: 450,
          width: 120,
          height: 40,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'idea4',
          text: 'Idea 4',
          type: 'CHILD',
          parentId: 'root',
          positionX: 600,
          positionY: 450,
          width: 120,
          height: 40,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
      ],
      connections: [
        { id: 'c1', sourceNodeId: 'root', targetNodeId: 'idea1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c2', sourceNodeId: 'root', targetNodeId: 'idea2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c3', sourceNodeId: 'root', targetNodeId: 'idea3', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c4', sourceNodeId: 'root', targetNodeId: 'idea4', type: 'HIERARCHICAL', label: null, style: {} },
      ],
      settings: {},
    },
  },
  {
    name: 'SWOT Analysis',
    description: 'Strengths, Weaknesses, Opportunities, and Threats analysis template',
    category: 'Business',
    thumbnail: null,
    isPublic: true,
    data: {
      nodes: [
        {
          id: 'root',
          text: 'SWOT Analysis',
          type: 'ROOT',
          parentId: null,
          positionX: 400,
          positionY: 300,
          width: 150,
          height: 50,
          style: { backgroundColor: '#8b5cf6', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'strengths',
          text: 'Strengths',
          type: 'CHILD',
          parentId: 'root',
          positionX: 150,
          positionY: 150,
          width: 130,
          height: 45,
          style: { backgroundColor: '#22c55e', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'weaknesses',
          text: 'Weaknesses',
          type: 'CHILD',
          parentId: 'root',
          positionX: 650,
          positionY: 150,
          width: 130,
          height: 45,
          style: { backgroundColor: '#ef4444', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'opportunities',
          text: 'Opportunities',
          type: 'CHILD',
          parentId: 'root',
          positionX: 150,
          positionY: 450,
          width: 130,
          height: 45,
          style: { backgroundColor: '#3b82f6', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'threats',
          text: 'Threats',
          type: 'CHILD',
          parentId: 'root',
          positionX: 650,
          positionY: 450,
          width: 130,
          height: 45,
          style: { backgroundColor: '#f97316', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 's1',
          text: 'Strength 1',
          type: 'CHILD',
          parentId: 'strengths',
          positionX: 50,
          positionY: 80,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'w1',
          text: 'Weakness 1',
          type: 'CHILD',
          parentId: 'weaknesses',
          positionX: 750,
          positionY: 80,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'o1',
          text: 'Opportunity 1',
          type: 'CHILD',
          parentId: 'opportunities',
          positionX: 50,
          positionY: 520,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 't1',
          text: 'Threat 1',
          type: 'CHILD',
          parentId: 'threats',
          positionX: 750,
          positionY: 520,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
      ],
      connections: [
        { id: 'c1', sourceNodeId: 'root', targetNodeId: 'strengths', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c2', sourceNodeId: 'root', targetNodeId: 'weaknesses', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c3', sourceNodeId: 'root', targetNodeId: 'opportunities', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c4', sourceNodeId: 'root', targetNodeId: 'threats', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c5', sourceNodeId: 'strengths', targetNodeId: 's1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c6', sourceNodeId: 'weaknesses', targetNodeId: 'w1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c7', sourceNodeId: 'opportunities', targetNodeId: 'o1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c8', sourceNodeId: 'threats', targetNodeId: 't1', type: 'HIERARCHICAL', label: null, style: {} },
      ],
      settings: {},
    },
  },
  {
    name: 'Project Plan',
    description: 'A template for planning project phases and tasks',
    category: 'Project Management',
    thumbnail: null,
    isPublic: true,
    data: {
      nodes: [
        {
          id: 'root',
          text: 'Project Name',
          type: 'ROOT',
          parentId: null,
          positionX: 400,
          positionY: 50,
          width: 150,
          height: 50,
          style: { backgroundColor: '#0ea5e9', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'phase1',
          text: 'Phase 1: Planning',
          type: 'CHILD',
          parentId: 'root',
          positionX: 100,
          positionY: 150,
          width: 150,
          height: 45,
          style: { backgroundColor: '#f59e0b' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'phase2',
          text: 'Phase 2: Development',
          type: 'CHILD',
          parentId: 'root',
          positionX: 400,
          positionY: 150,
          width: 150,
          height: 45,
          style: { backgroundColor: '#10b981' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'phase3',
          text: 'Phase 3: Launch',
          type: 'CHILD',
          parentId: 'root',
          positionX: 700,
          positionY: 150,
          width: 150,
          height: 45,
          style: { backgroundColor: '#6366f1' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'task1',
          text: 'Define requirements',
          type: 'CHILD',
          parentId: 'phase1',
          positionX: 50,
          positionY: 250,
          width: 130,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'task2',
          text: 'Create timeline',
          type: 'CHILD',
          parentId: 'phase1',
          positionX: 200,
          positionY: 250,
          width: 130,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'task3',
          text: 'Build features',
          type: 'CHILD',
          parentId: 'phase2',
          positionX: 350,
          positionY: 250,
          width: 130,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'task4',
          text: 'Testing',
          type: 'CHILD',
          parentId: 'phase2',
          positionX: 500,
          positionY: 250,
          width: 130,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'task5',
          text: 'Deploy',
          type: 'CHILD',
          parentId: 'phase3',
          positionX: 650,
          positionY: 250,
          width: 130,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'task6',
          text: 'Monitor',
          type: 'CHILD',
          parentId: 'phase3',
          positionX: 800,
          positionY: 250,
          width: 130,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
      ],
      connections: [
        { id: 'c1', sourceNodeId: 'root', targetNodeId: 'phase1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c2', sourceNodeId: 'root', targetNodeId: 'phase2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c3', sourceNodeId: 'root', targetNodeId: 'phase3', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c4', sourceNodeId: 'phase1', targetNodeId: 'task1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c5', sourceNodeId: 'phase1', targetNodeId: 'task2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c6', sourceNodeId: 'phase2', targetNodeId: 'task3', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c7', sourceNodeId: 'phase2', targetNodeId: 'task4', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c8', sourceNodeId: 'phase3', targetNodeId: 'task5', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c9', sourceNodeId: 'phase3', targetNodeId: 'task6', type: 'HIERARCHICAL', label: null, style: {} },
      ],
      settings: {},
    },
  },
  {
    name: 'Meeting Notes',
    description: 'Template for organizing meeting notes with agenda, attendees, and action items',
    category: 'General',
    thumbnail: null,
    isPublic: true,
    data: {
      nodes: [
        {
          id: 'root',
          text: 'Meeting Title',
          type: 'ROOT',
          parentId: null,
          positionX: 400,
          positionY: 50,
          width: 150,
          height: 50,
          style: { backgroundColor: '#ec4899', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'agenda',
          text: 'Agenda',
          type: 'CHILD',
          parentId: 'root',
          positionX: 100,
          positionY: 150,
          width: 120,
          height: 40,
          style: { backgroundColor: '#f97316' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'attendees',
          text: 'Attendees',
          type: 'CHILD',
          parentId: 'root',
          positionX: 400,
          positionY: 150,
          width: 120,
          height: 40,
          style: { backgroundColor: '#14b8a6' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'actions',
          text: 'Action Items',
          type: 'CHILD',
          parentId: 'root',
          positionX: 700,
          positionY: 150,
          width: 120,
          height: 40,
          style: { backgroundColor: '#ef4444' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'topic1',
          text: 'Topic 1',
          type: 'CHILD',
          parentId: 'agenda',
          positionX: 50,
          positionY: 250,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'topic2',
          text: 'Topic 2',
          type: 'CHILD',
          parentId: 'agenda',
          positionX: 170,
          positionY: 250,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'person1',
          text: 'Person 1',
          type: 'CHILD',
          parentId: 'attendees',
          positionX: 350,
          positionY: 250,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'person2',
          text: 'Person 2',
          type: 'CHILD',
          parentId: 'attendees',
          positionX: 470,
          positionY: 250,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'action1',
          text: 'Action 1',
          type: 'CHILD',
          parentId: 'actions',
          positionX: 650,
          positionY: 250,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'action2',
          text: 'Action 2',
          type: 'CHILD',
          parentId: 'actions',
          positionX: 770,
          positionY: 250,
          width: 100,
          height: 35,
          style: {},
          metadata: {},
          isCollapsed: false,
        },
      ],
      connections: [
        { id: 'c1', sourceNodeId: 'root', targetNodeId: 'agenda', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c2', sourceNodeId: 'root', targetNodeId: 'attendees', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c3', sourceNodeId: 'root', targetNodeId: 'actions', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c4', sourceNodeId: 'agenda', targetNodeId: 'topic1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c5', sourceNodeId: 'agenda', targetNodeId: 'topic2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c6', sourceNodeId: 'attendees', targetNodeId: 'person1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c7', sourceNodeId: 'attendees', targetNodeId: 'person2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c8', sourceNodeId: 'actions', targetNodeId: 'action1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c9', sourceNodeId: 'actions', targetNodeId: 'action2', type: 'HIERARCHICAL', label: null, style: {} },
      ],
      settings: {},
    },
  },
  {
    name: 'Decision Tree',
    description: 'Template for mapping out decisions and their outcomes',
    category: 'Decision Making',
    thumbnail: null,
    isPublic: true,
    data: {
      nodes: [
        {
          id: 'root',
          text: 'Decision',
          type: 'ROOT',
          parentId: null,
          positionX: 400,
          positionY: 50,
          width: 150,
          height: 50,
          style: { backgroundColor: '#8b5cf6', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'option1',
          text: 'Option A',
          type: 'CHILD',
          parentId: 'root',
          positionX: 200,
          positionY: 150,
          width: 120,
          height: 40,
          style: { backgroundColor: '#3b82f6' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'option2',
          text: 'Option B',
          type: 'CHILD',
          parentId: 'root',
          positionX: 600,
          positionY: 150,
          width: 120,
          height: 40,
          style: { backgroundColor: '#22c55e' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'pro1',
          text: 'Pros',
          type: 'CHILD',
          parentId: 'option1',
          positionX: 100,
          positionY: 250,
          width: 100,
          height: 35,
          style: { backgroundColor: '#22c55e' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'con1',
          text: 'Cons',
          type: 'CHILD',
          parentId: 'option1',
          positionX: 220,
          positionY: 250,
          width: 100,
          height: 35,
          style: { backgroundColor: '#ef4444' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'pro2',
          text: 'Pros',
          type: 'CHILD',
          parentId: 'option2',
          positionX: 500,
          positionY: 250,
          width: 100,
          height: 35,
          style: { backgroundColor: '#22c55e' },
          metadata: {},
          isCollapsed: false,
        },
        {
          id: 'con2',
          text: 'Cons',
          type: 'CHILD',
          parentId: 'option2',
          positionX: 620,
          positionY: 250,
          width: 100,
          height: 35,
          style: { backgroundColor: '#ef4444' },
          metadata: {},
          isCollapsed: false,
        },
      ],
      connections: [
        { id: 'c1', sourceNodeId: 'root', targetNodeId: 'option1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c2', sourceNodeId: 'root', targetNodeId: 'option2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c3', sourceNodeId: 'option1', targetNodeId: 'pro1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c4', sourceNodeId: 'option1', targetNodeId: 'con1', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c5', sourceNodeId: 'option2', targetNodeId: 'pro2', type: 'HIERARCHICAL', label: null, style: {} },
        { id: 'c6', sourceNodeId: 'option2', targetNodeId: 'con2', type: 'HIERARCHICAL', label: null, style: {} },
      ],
      settings: {},
    },
  },
  {
    name: 'Mind Map',
    description: 'A blank mind map template with a central topic',
    category: 'General',
    thumbnail: null,
    isPublic: true,
    data: {
      nodes: [
        {
          id: 'root',
          text: 'Central Idea',
          type: 'ROOT',
          parentId: null,
          positionX: 400,
          positionY: 300,
          width: 150,
          height: 50,
          style: { backgroundColor: '#3b82f6', textColor: '#ffffff' },
          metadata: {},
          isCollapsed: false,
        },
      ],
      connections: [],
      settings: {},
    },
  },
];

async function main() {
  console.log('Seeding templates...');

  for (const template of defaultTemplates) {
    const existing = await prisma.template.findFirst({
      where: { name: template.name, isPublic: true },
    });

    if (!existing) {
      await prisma.template.create({
        data: template,
      });
      console.log(`Created template: ${template.name}`);
    } else {
      console.log(`Template already exists: ${template.name}`);
    }
  }

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
